tinyMCE.addI18n('fr.advimage_dlg',{
tab_general:"G\u00E9n\u00E9ral",
tab_appearance:"Options",
tab_advanced:"Avanc\u00E9",
general:"G\u00E9n\u00E9ral",
title:"Titre",
preview:"Pr\u00E9visualisation",
constrain_proportions:"Conserver les proportions",
langdir:"Sens de lecture",
langcode:"Code de la langue",
long_desc:"Description longue du lien",
style:"Code HTML",
classes:"Classes",
ltr:"De gauche \u00E0 droite",
rtl:"De droite \u00E0 gauche",
id:"Id",
map:"Carte image",
swap_image:"Alterner image",
alt_image:"Image alternative",
mouseover:"au passage de la souris",
mouseout:"\u00E0 la sortie de la souris",
misc:"Divers",
example_img:"Apparence de l'image",
missing_alt:"\u00CAtes-vous s\u00FBr de vouloir continuer sans inclure de 'texte alternatif'?\nSans celà, l'image pourrait ne pas \u00EAtre accessible :\naux personnes handicap\u00E9s visuellement,\naux navigateurs bloquant les images \nou si l'image n'est plus disponible sur le serveur.",
dialog_title:"Ins\u00E9rer/D\u00E9poser une image",
src:"Fichier",
alt:"Texte alternatif",
list:"Liste d'images",
border:"Bordure",
dimensions:"Dimensions",
vspace:"Espacement vertical",
hspace:"Espacement horizontal",
align:"Habillage",
align_baseline:"Base",
align_top:"Haut",
align_middle:"Milieu",
align_bottom:"Bas",
align_texttop:"Haut du texte",
align_textbottom:"Bas du texte",
align_left:"Gauche",
align_right:"Droite",
image_list:"Liste d'images"
});