<h2>{formation.retNom}</h2>
    <ul>
    <!--[modules+]-->
    <li>{module.retNom}
        <ul>
        <!--[rubriques+]-->
        <li>{rubrique.retNom}
            <ul>
            <!--[activites+]-->
            <li>{activite.retNom}
                <ul>
                <!--[sousActivites+]-->
                <li>{sousActivite.retNom}</li>
                <!--[sousActivites-]-->
                </ul>
            </li>
            <!--[activites-]-->
            </ul>
        </li>
        <!--[rubriques-]-->
        </ul>
    </li>
    <!--[modules-]-->
    </ul>